version: "3"
services:
  server: 
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: radicon-run-server
    ports:
      - "25000:5000"
    volumes:
      - ./server/src:/src/
    tty: true
  